name: Daily VapeSourcing RSS

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write  # workflow 有 push 权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run RSS Script
        run: python vapesourcingRSS.py

      - name: Deploy RSS to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./        # RSS 文件在仓库根目录
          publish_branch: gh-pages
          keep_files: true       # 保留 gh-pages 分支已有文件


